server:
  port: 8081
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: akagami.no.shanks71821@gmail.com
    password: waogsatyjbbmksevon
    name: Hirely
  datasource:
    url: jdbc:postgresql://localhost:5432/hirely?reWriteBatchedInserts=true
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 25
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
      file-size-threshold: 2KB
management:
  endpoints:
    web:
      exposure:
        include: mappings
app:
  cors:
    allowed-origin: http://localhost:8080
  upload:
    resume:
      root-dir: uploads
      max-file-size: 10MB
      allowed-file-types:
        - application/pdf
        - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    image:
      max-file-size: 1MB
      allowed-file-types:
        - image/png
        - image/jpeg
        - image/webp
  jwt:
    secret-base64: ZDLlXLDRfPqKkcYdZfXalFXYEvL5dxm2dbAUcdE83uy # atleast 256 bits
    expirationMs: 86400000

logging:
  level:
    org:
      springframework:
        security: DEBUG
